openapi: 3.1.0
info:
  version: v1.3
  title: Claim API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-logo:
    url: https://assets.qoala.app/qoala/email-transparant.png
  description: "# Introduction\n\nWelcome to the Qoala API! Our API provides you with access to the Qoala\
    \ platform, allowing you to perform actions like creating policies across various product categories\
    \ and submitting new claims, among other functionalities.\nFor your convenience, we have included\
    \ a straightforward example in the payload to assist you in seamlessly integrating with our platform.\
    \ You can also find code examples in the shaded area on the right.\nIf you have any inquiries or need\
    \ assistance with our API, please do not hesitate to contact our dedicated developer support team.\
    \ We are here to assist you!\n\n# Product Categories\n\nQoala, functioning as an insurance broker,\
    \ offers a diverse range of insurance products that encompass various functionalities and benefits.\
    \ Consequently, we have organized these products into distinct groups based on their corresponding\
    \ functions. There are four primary categories into which we classify these products:\n\n1. Travel\n\
    The Travel category encompasses the following subcategories:\n\n- Flight\n- Train\n- Bus\n- Hotel\n\
    - Experience\n\n2. Gadget\nThe Gadget category includes the following subcategories:\n\n- Smartphone\n\
    - Electronic\n\n3. Finance\n\n4. Health\n\n>It's important to note that Finance and Health do not\
    \ have any subcategories at this time.\n\n# Host\n\nEnvironment|Host Address\n------------- | -------------\n\
    Staging|https://api-staging.qoala.app\nProduction|https://api.qoala.app\n\n# Authentication\n\nQoala\
    \ Partnership utilizes API keys to grant access to the API. You can request a new API key from Qoala\
    \ Engineering. \nQoala Partnership requires the API key to be included in the header of all API requests\
    \ made to our services. The header should appear as follows:\n`x-api-key: abcdefg`\n\n> To use the\
    \ x-api-key, refer to the example below:\n\n```shell\ncurl --location --request {METHOD} '{{HOST_URL}}'\
    \ \\\n--header 'x-api-key: abcdefg' \\\n--header 'Content-Type: application/json' \\\n--data-raw '{}'\n\
    ```\n\n> Make sure to replace `abcdefg` with your API key.\n"
servers:
- url: https://api-staging.qoala.app
- url: https://api.uat.qoala.app
- url: https://api.qoala.app
security:
- ApiKeyAuth: []
tags:
- name: API Specification
  description: Claim API documentation consist of create claim, get claim detail or status, claim cancellation
    and claim pool detail or update claim documents
paths:
  /api/v2/claims/partner/create:
    post:
      tags:
      - API Specification
      summary: Create Claim
      description: 'Partners could use this endpoint to generate and create a new claim. Qoala will validate
        and make sure the policy is claimable. Qoala will share the claim number in the response and if
        needed could also notify the partner via callback Integration.

        ### List of Claim Status


        | Status Code                | Claim Status (Subject)          | Description                                     |

        | --------------------------- | ------------------------------- | -----------------------------------------------
        |

        | `CLAIM_INITIATE`            | Claim initiated                 | When the claimer successfully
        submitted a claim |

        | `QOALA_CLAIM_APPROVE`       | Claim received by Qoala         | Qoala approved the claim                        |

        | `QOALA_CLAIM_REJECT`        | Claim rejected by Qoala         | Qoala rejects the claim                         |

        | `INSURANCE_CLAIM_APPROVE`   | Claim approved by Insurance      | Insurance approved the claim                    |

        | `INSURANCE_CLAIM_REJECT`    | Claim rejected by Insurance      | Insurance rejected the claim                    |

        | `INSURANCE_CLAIM_PAID`      | Claim paid by Insurance           | Claim already paid by insurance                 |

        | `INSURANCE_CLAIM_WAITING_PAID` | Claim Waiting paid            | Claim already approved by insurance
        and waiting for paid |


        Each status code corresponds to a specific claim status, providing information about the state
        of the claim in the system.

        '
      operationId: createClaim
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Claim Service success
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      number:
                        type: string
                        example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                      policy_number:
                        type: string
                        example: T-FLIGHT-PARTNER-001-20230824-OM94T
                      last_status:
                        type: string
                        example: CLAIM_INITIATE
                      created_at:
                        type: string
                        format: date-time
                        example: '2024-07-18T10:30:00Z'
              examples:
                Success:
                  $ref: '#/components/examples/createClaimPartnerResponse200'
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: http code response
                    example: 400
                  error_code:
                    type: string
                    description: "qoala system error code for error classification\n    \n### List of\
                      \ Error Code detail\n\n|Error Code | HTTP Status | Description|\n|----------|-------------|------------|\n\
                      |CLAIM-CREATE-001 | 400 | Invalid Body request|\n|CLAIM-CREATE-003 | 400 | Policy\
                      \ Not Available|\n|CLAIM-CREATE-004 | 400 | Product Not Found|\n|CLAIM-CREATE-006\
                      \ | 400 | Failed claim Reach maximum Limitation|\n|CLAIM-CREATE-007 | 400 | Invalid\
                      \ Time|\n|CLAIM-CREATE-018 | 400 | Benefit Code Not Valid|\n"
                    example: CLAIM-CREATE-006
                  message:
                    type: string
                    description: status of response, it will contain failed
                    example: failed claim, reach maximum limitation
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    description: http code response
                    example: 401
                  error_code:
                    type: string
                    description: 'qoala system error code for invalid token


                      ### List of Error Code detail

                      | Error Code | HTTP Status | Description |

                      |---|---|---|

                      | QC-CLT-KEYA-V1-003 | 401 | Invalid Permission |

                      '
                    example: QEC-ERR-401-01
                  message:
                    type: string
                    description: short message explains about the failed response
                    example: invalid unauthorized
                  status:
                    type: string
                    description: status of response, it will contain failed
                    example: failed
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    description: http code response
                    example: 500
                  error_code:
                    type: string
                    description: 'qoala system error code for error classification


                      ### List of Error Code detail

                      |Error Code | HTTP Status | Description|

                      |----------|-------------|------------|

                      |CLAIM-CREATE-008 | 500 | Failed claim Reach maximum Limitation in Benefit Level|

                      '
                    example: CLAIM-ERR-001
                  message:
                    type: string
                    description: short message explains about the failed response
                    example: internal server error
                  status:
                    type: string
                    description: status of response, it will contain failed
                    example: failed
              examples:
                Internal Server Error:
                  $ref: '#/components/examples/createClaimPartnerResponse500'
      requestBody:
        content:
          application/json:
            examples:
              Claim for Travel Product:
                $ref: '#/components/examples/createClaimTravelProduct'
              Claim for Credit Insurance With Reinstatement:
                $ref: '#/components/examples/createClaimCreditInsuranceWithReinstatement'
            schema:
              type: object
              required:
              - currency_code
              - country_code
              - policy_number
              - user_channel
              - partner_code
              - product
              - total_amount
              properties:
                currency_code:
                  description: Claim currency
                  type: string
                  example: IDR
                country_code:
                  description: Claim country code
                  type: string
                  example: ID
                total_amount:
                  type: number
                  description: "Total Claim amount\n *for finance product the value is equal to outstanding\
                    \ amount"
                user_channel:
                  description: Channel where the claim comes from
                  type: string
                  example: PARTNERSHIP
                partner_code:
                  description: Partner code predefined by Qoala
                  type: string
                  example: ABC
                partner_claim_id:
                  description: Unique claim identifier generated by the partner system
                  type: string
                  example: C12345
                policy_number:
                  description: Unique policy number generated by the Qoala system
                  type: string
                  example: F-CRDT-PARTNER-001-20230802-OM94T
                product:
                  description: Product information
                  type: object
                  required:
                  - category
                  - code
                  - benefit_code
                  properties:
                    category:
                      type: string
                      enum:
                      - GADGET
                      - TRAVEL
                      - FINANCE
                      - MICROHEALTH
                    code:
                      type: string
                      example: PA-123
                      description: Product code generated by Qoala
                    benefit_code:
                      type: string
                      example: BE-1234
                      description: Benefit Code generated by Qoala
                claimant_data:
                  description: Claimant information
                  type: object
                  required:
                  - full_name
                  properties:
                    full_name:
                      type: string
                      description: Claimant full name
                    phone_number:
                      type: string
                      description: Claimant phone number
                form_data:
                  description: Claim form Data
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Alamat
                        description: name of data
                      value:
                        type: string
                        example: 85778
                        description: value of data
                covered_data:
                  description: insureds information
                  type: array
                  items:
                    type: object
                    $ref: '#/components/schemas/Insured'
                claim_additional_info:
                  description: Claim additional info only applicable for specific product category
                  type: object
                  properties:
                    loan_id:
                      type: string
                      description: partner transaction number or loan id // required for Credit Insurance
                        with reinstatement product
                    borrower_name:
                      type: string
                      description: Borrower name // required for Credit Insurance with reinstatement product
                    beneficiary_name:
                      type: string
                      description: Beneficiary or lender name // required for Credit Insurance with reinstatement
                        product
                    last_payment_date:
                      type: string
                      description: last payment date, if the loan hasnt been paid or loan is less than
                        30 days please put loan start date // required for Credit Insurance with reinstatement
                        product
                    last_collection_date:
                      type: string
                      description: last collection date from the partner // required for Credit Insurance
                        with reinstatement product
                    outstanding_amount:
                      type: number
                      description: remaining loan
        description: Payload for creating claim // required for Credit Insurance with reinstatement product
        required: true
  /api/v2/claims/partner/cancel:
    patch:
      tags:
      - API Specification
      summary: Cancel Claim
      description: Claim cancellation
      operationId: cancelClaim
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Claim Service success
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      claim_number:
                        type: string
                        example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                      status:
                        type: string
                        example: CLAIM_CANCELLED
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 401
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Unauthorized token
                  error_code:
                    type: string
                    example: QC-CLT-KEYA-V1-003
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  error_code:
                    type: string
                    example: CLAIM-ERR-001
                  message:
                    type: string
                    example: internal server error
                  status:
                    type: string
                    example: failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                claim_number:
                  type: string
                  description: unique identifier for claim created by qoala system
                  example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                parent_category:
                  type: string
                  example: microhealth
                  description: category of product
                  enum:
                  - microhealth
                  - finance
                  - gadget
                  - travel
                reason:
                  type: string
                  description: explain the reason for cancellation briefly
                  example: wrong claim number
        description: Payload for cancelling claim
        required: true
  /api/v2/claims/partner/update/presign:
    post:
      tags:
      - API Specification
      summary: Upload claim documents
      description: Presign url to upload document
      operationId: presignCreateClaim
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Claim Service success
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      claim_number:
                        type: string
                        description: claim unique number generated by qoala system
                        example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                      status:
                        type: string
                        description: last status of claim
                        example: CLAIM_SUBMITTED
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 401
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Unauthorized token
                  error_code:
                    type: string
                    example: QC-CLT-KEYA-V1-003
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  error_code:
                    type: string
                    example: CLAIM-ERR-001
                  message:
                    type: string
                    example: internal server error
                  status:
                    type: string
                    example: failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                claim_number:
                  type: string
                  description: unique identifier for claim created by qoala system
                  example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                file_name:
                  type: string
                  example: fileName-1234.png
                  description: Document name
                type:
                  type: string
                  description: type of document
                  example: NATIONAL_ID
        description: Payload for creating presigned url claim
        required: true
    put:
      tags:
      - API Specification
      summary: Update claim documents
      description: Presign url to upload document
      operationId: presignUploadClaim
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Claim Service success
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      claim_number:
                        type: string
                        description: claim unique number generated by qoala system
                        example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                      status:
                        type: string
                        description: last status of claim
                        example: CLAIM_SUBMITTED
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 401
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Unauthorized token
                  error_code:
                    type: string
                    example: QC-CLT-KEYA-V1-003
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  error_code:
                    type: string
                    example: CLAIM-ERR-001
                  message:
                    type: string
                    example: internal server error
                  status:
                    type: string
                    example: failed
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
              maxLength: 12345
        description: Payload for creating presigned url claim
        required: true
  /api/v2/products/finance/partner/products/stoploss/{claim_pool_code}:
    get:
      tags:
      - API Specification
      summary: Get Claim Pool
      description: this endpoint can be used by the partner to get the claim pool balance
      operationId: getPool
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Success get stoploss detail
                  code:
                    type: number
                    example: 200
                  data:
                    type: object
                    properties:
                      code:
                        type: string
                        description: unique code for certain claim pool
                        example: CLAIM_POOL_CODE
                      partner_code:
                        type: string
                        description: partner code associated for certain claim pool
                        example: PARTNER_CODE
                      insurance_code:
                        type: string
                        description: insurance code associated for certain claim pool
                        example: INSURANCE_CODE
                      total_stoploss_amount:
                        type: number
                        description: Total claim pool collected
                        format: float64
                        example: 1621256
                      total_pending_claim_amount:
                        type: number
                        description: Total approved claim but haven't been disbursed (will be disburse
                          in the next day)
                        format: float64
                        example: 1621256
                      total_claim_amount:
                        type: number
                        description: Total claim pool has been claimed
                        format: float64
                        example: 1621256
                      total_balance:
                        type: number
                        description: Available amount claim pool
                        format: float64
                        example: 1621256
                      total_available_claim_pool:
                        type: number
                        format: float64
                        example: 1621256
                      products_code:
                        type: array
                        description: List of products associated with this claim pool code
                        items:
                          type: string
                        example:
                        - F-CRDT-PARTNER-001
                        - F-CRDT-PARTNER-002
                      created_at:
                        type: string
                        description: when the claim pool is created
                        format: date-time
                      updated_at:
                        type: string
                        description: when the last update claim pool
                        format: date-time
        '400':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 400
                  error_code:
                    type: string
                    example: CLAIM-CREATE-006
                  message:
                    type: string
                    example: failed claim, reach maximum limitation
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 401
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: Unauthorized request
                  data:
                    type: object
                    example: null
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  error_code:
                    type: string
                    example: QES-ERR-001
                  message:
                    type: string
                    example: internal server error
                  status:
                    type: string
                    example: failed
      parameters:
      - in: path
        name: claim_pool_code
        required: true
        description: Claim Pool code generated by Qoala
        schema:
          type: string
          example: CLAIM_POOL_CODE
  /api/v2/claims/partner/status:
    get:
      tags:
      - API Specification
      summary: Get Claim Status
      description: Get claim status
      operationId: statusClaim
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200status'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 400
                  error_code:
                    type: string
                    example: CLAIM-GET-001
                  message:
                    type: string
                    example: Invalid Params
                  status:
                    type: string
                    example: failed
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 401
                  error_code:
                    type: string
                    example: QC-CLT-KEYA-V1-003
                  message:
                    type: string
                    example: Invalid Permission
                  status:
                    type: string
                    example: failed
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 404
                  error_code:
                    type: string
                    example: CLAIM-GET-005
                  message:
                    type: string
                    example: not found
                  status:
                    type: string
                    example: failed
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 500
                  error_code:
                    type: string
                    example: CLAIM-GET-003
                  message:
                    type: string
                    example: internal server error
                  status:
                    type: string
                    example: failed
      parameters:
      - in: query
        name: policy_number
        required: false
        description: Unique identifier for policy generated by qoala system. Policy number is optinal
          parameter only if claim number is provided in the URL.
        schema:
          type: string
          example: F-CRDT-1029
      - in: query
        name: claim_number
        required: true
        description: Unique identifier for claim created by qoala system. Claim number is optional parameter
          only if policy number is provided in the URL
        schema:
          type: string
          example: C-20240718-TFLIGHTPARTNER001-CXVAC2
components:
  schemas:
    Document:
      type: object
      properties:
        file_name:
          description: name of the fale, you can provide the filename include its extention.
          type: string
          example: T-FLIGHT-PARTNER-001-20230824-OM94T.pdf
        type:
          description: type of document, it is just constant value that categorize of the document.
          type: string
          examples:
          - POLICY_CERTIFICATE
          - POLICY_WORDING
          - KTP
          - ID
          - TICKET
          - and soon
        url:
          description: full url to access the document, this is should be public url
          type: string
          example: '{base_url}/api/v2/policies/documents/bea04405-97d2-4eb8-b4f6-8db76e6f17ac/files/T-FLIGHT-PARTNER-001-20230824-OM94T.pdf'
        alias:
          description: document alias
          type: string
          example: policy_certificate.pdf
    InsuredTravel:
      required:
      - identity_type
      - identity_number
      - booking_time
      - name
      - departure_time
      - arrival_time
      type: object
      properties:
        identity_type:
          type: string
          example: BOOKING_NUMBER
        identity_number:
          type: string
          example: 280323142127
        booking_time:
          type: string
          example: '2023-02-15T10:00:00Z'
          format: date-time
        name:
          type: string
          example: Garuda Indonesia
        number:
          type: string
          example: GA-654
        departure:
          type: string
          example: CGK
        departure_time:
          type: string
          example: '2023-03-01T22:15:00+07:00'
          format: date-time
        arrival:
          type: string
          example: UPG
        arrival_time:
          type: string
          example: '2023-03-02T01:50:00+09:00'
        class:
          type: string
          example: Economy
        sub_class:
          type: string
          example: J
        city_origin:
          type: string
          example: Jakarta
        city_destination:
          type: string
          example: Makassar
        country_origin:
          type: string
          example: Indonesia
        country_destination:
          type: string
          example: Indonesia
        timezone_origin:
          type: string
          example: Asia/Jakarta
        timezone_destination:
          type: string
          example: Asia/Pontianak
        total_price_ticket:
          type: number
          format: float64
          example: 4145300
        sub_total_price_ticket:
          type: number
          format: float64
          example: 4145300
        trip_type:
          type: string
          description: trip information
          enum:
          - SINGLETRIP
          - ROUNDTRIP-1
          - ROUNDTRIP-2
        trip_order:
          type: number
          format: int
          example: 1
        number_of_room:
          type: number
          format: int
          example: 2
        additional_info:
          type: object
    InsuredUser:
      type: object
      properties:
        identity_type:
          type: string
          example: ID_CARD
          description: identifier type of user information
        identity_number:
          type: string
          example: 12010367678988002
          description: unique identifier of user information
        full_name:
          type: string
          example: Judiwara Samson
          description: full name of user information
        email:
          type: string
          example: john.doe@qoala.id
          description: email address of user information
        phone_number:
          type: string
          example: 81245678910
          description: phone number of user
        birth_date:
          type: string
          example: 13-11-2000
          description: birth date of user
        gender:
          description: Policy Holder Gender
          type: string
          example: FEMALE
          enum:
          - FEMALE
          - MALE
        relationship:
          type: string
          example: Wife
          description: relationship of user within group of insured user in one transaction
        address:
          type: string
          example: Jl. Sudirman No. 10, Kelurahan Menteng, Kecamatan Menteng, Kota Jakarta Pusat, DKI
            Jakarta 10310
          description: detail address of user
        occupation:
          type: string
          example: Software Engineer
          description: occupation of user
        additional_info:
          type: object
          example:
            passenger_type: ADULT
            city: Jakarta
            country: Indonesia
            zipcode: '14045'
            subject: sender
          description: additional optional information
    InsuredLoan:
      type: object
      properties:
        identity_type:
          type: string
          example: LOAN_NUMBER
        identity_number:
          type: string
          example: LOAN-NUMBER123456
        loan_amount:
          type: number
          format: float64
          example: 100000000
        loan_total_principal:
          type: number
          format: float64
          example: 10000
        loan_total_principal_percentage:
          type: number
          format: float64
          example: 10000
        tenure_value:
          type: number
          format: float64
          example: 90
        tenure_period:
          type: string
          example: DAYS
        interest_rate:
          type: number
          format: float64
          example: 9.4
        interest_period:
          type: string
          example: YEAR
        additional_info:
          type: object
          example: {}
    InsuredGadget:
      required:
      - identity_type
      - identity_number
      - sum_insured
      - brand
      - model
      - device_category
      type: object
      properties:
        identity_type:
          type: string
          example: IMEI
          description: type of device identification
        identity_number:
          type: string
          example: 517236118991231800
          description: value of device identification
        sum_insured:
          type: number
          format: float64
          example: 100000
          description: amount of insured
        manufacturer:
          type: string
          example: Apple
          description: manufacture of device
        brand:
          type: string
          example: Apple
          description: brand of device
        series:
          type: string
          example: A2643
          description: series of device
        model:
          type: string
          example: Iphone 13 Pro Max
          description: model of device
        activation_number:
          type: string
          example: 876543345687654
          description: activation number of device
        external_url:
          type: string
          example: http://url_here
          description: external url for activation
        upload_activation_at:
          type: string
          format: date-time
          example: '2022-10-11T00:00:00Z'
          description: time of activation
        device_category:
          type: string
          example: SMARTPHONE
          enum:
          - SMARTPHONE
          - TABLET
          - SMARTWATCH
          - LAPTOP
          - OTHERS
          description: category of device
        device_price:
          type: number
          format: float64
          example: 10000000
          description: price of device
        deductible_info:
          type: object
          description: information of deduction
          properties:
            unit_fee:
              type: string
              enum:
              - STATIC
              - PERCENTAGE
            unit_fee_amount:
              type: number
              format: float64
              example: 910
        covered_type_unit:
          type: string
          example: MONTH
          description: unit of covered type
          enum:
          - DAY
          - MONTH
          - YEAR
        covered_type_max:
          type: number
          example: 1
          description: maximum number of covered period or tenure
    InsuredMotor:
      type: object
      properties:
        identity_type:
          type: string
          example: LOAN_NUMBER
        identity_number:
          type: string
          example: LOAN-NUMBER123456
        manufacturer:
          type: string
          example: Yamaha
        brand:
          type: string
          example: Yamaha
        series:
          type: string
          example: R6
        condition:
          type: string
          example: new
        chasis_number:
          type: string
          example: 2
        engine_number:
          type: string
          example: 5647890356765432
        registration_number:
          type: string
          example: 82347694354533
        year:
          type: number
          format: int
          example: 2022
        price:
          type: number
          format: float64
          example: 20000000
    InsuredShipping:
      required:
      - identity_type
      - identity_number
      type: object
      properties:
        carrier:
          type: string
          example: JNE
          description: 'Name of carrier that provide shipping service example: JNE, FEDEX, etc'
        identity_type:
          type: string
          example: TRACKING_NUMBER
          description: Identifier type of shipping
        identity_number:
          type: string
          example: 280323142127
          description: Unique value as identifier number to differentiate each shipping
        service:
          type: string
          example: Reguler, Sameday, Instant
          description: Type of service offered by shipping provide
        cost:
          type: number
          example: 10000
          description: Price of shipping service
        total_package_price:
          type: number
          example: 50000
          description: Total package price
        estimated_delivery_time:
          type: string
          example: '2023-02-15T10:00:00Z'
          format: date-time
          description: Time estimation when the package will be received by the recipient
    InsuredPackage:
      required:
      - identity_type
      - identity_number
      type: object
      properties:
        name:
          type: string
          example: TV Samsung 12"
          description: Name of product
        identity_type:
          type: string
          example: BARCODE_NUMBER
          description: Identifier type of product
        identity_number:
          type: string
          example: '280323142127'
          description: Unique value as identifier number to differentiate each product
        price:
          type: number
          example: 20000
          description: Price of product
    InsuredVehicle:
      properties:
        identity_type:
          type: string
          example: PLATE_NUMBER
          description: Plate Number
        identity_number:
          type: string
          example: B1234QLA
          description: Identity number of the vehicle
        category:
          type: string
          example: CAR
          enum:
          - CAR
          - TRUCK
          - EV_MOTOR
          - MOTOR
          - EV_CAR
          description: category of vehicle
        manufacture:
          type: number
          format: string
          example: HONDA
          description: Vehicle Manufacturer
        model:
          type: string
          example: Ayla
          description: Vehicle Model
        manufacture_year:
          type: string
          example: '2023'
          description: Vehicle Manufacture Year
        color:
          type: string
          example: Blue
          description: Vehicle Color
        condition:
          type: string
          example: NEW
          description: Vehicle Condition
          enum:
          - NEW
          - USED
        plate_expiry_date:
          type: string
          example: 11/2024
          description: Plate Expiry Date
        chassis_number:
          type: string
          example: KSO1302345
          description: Chassis Number
        engine_number:
          type: string
          example: '1293293029300932'
          description: Engine Number
        accessories_note:
          type: string
          example: Spion, Roof Bar
          description: Accessories Note
        accessories_price:
          type: number
          example: 100000
          description: Accessories Price
        price:
          type: number
          example: 10000000
          description: Vehicle Price
        sum_insured:
          type: number
          example: 10000000
          description: Vehicle Sum Insured
        series:
          type: string
          example: 1.0 M/T-1000cc
          description: Vehicle Series
        engine:
          type: string
          example: '10000'
          description: Vehicle Engine Capacity
        inspection_type:
          type: string
          example: manual
          description: Inspection Type
        usage_type:
          type: string
          example: PERSONAL
          description: "Vehicle Usage type \n - Personal: The vehicle is used for personal, non-commercial\
            \ purposes. \n - Commercial: The vehicle is used for commercial purposes, such as business\
            \ or professional use."
          enum:
          - PERSONAL
          - COMMERCIAL
    InsuredGoods:
      required:
      - identity_type
      - identity_number
      - sum_insured
      - brand
      - model
      - category
      type: object
      properties:
        identity_type:
          type: string
          example: SERIAL_NUMBER
          enum:
          - SERIAL_NUMBER
          - PURCHASE_ID
          description: type of Goods identification
        identity_number:
          type: string
          example: 517236118991231800
          description: value of Goodse identification
        sum_insured:
          type: number
          format: float64
          example: 100000
          description: amount of insured
        price:
          type: number
          format: float64
          example: 100000
          description: goods price
        manufacturer:
          type: string
          example: Apple
          description: manufacture of device
        brand:
          type: string
          example: Rayban
          description: brand of goods
        model:
          type: string
          example: Iphone 13 Pro Max
          description: Goods Brand
        category:
          type: string
          example: EYWR
          description: Goods Category
          enum:
          - EYWR
          - FURN
          - MCHD
          - AUTO
          - TDMP
          - HOBY
          - RSKG
          - MBKG
    InsuredAgent:
      required:
      - identity_type
      - identity_number
      - store_id
      type: object
      properties:
        identity_type:
          type: string
          example: AGENT_ID
          description: identifier type of user information
        identity_number:
          type: string
          example: 12010367678988002
          description: unique identifier of user information
        full_name:
          type: string
          example: Judiwara Samson
          description: full name of user information
        email:
          type: string
          example: john.doe@qoala.id
          description: email address of user information
        phone_number:
          type: string
          example: 81245678910
          description: phone number of user
        store_location:
          type: string
          example: Indonesian Mall, Jakarta
          description: Address of the store
        store_name:
          type: string
          example: Eyewear Store
          description: Store Name
        store_id:
          type: string
          example: 12349
          description: Store Id
    Insured:
      type: object
      required:
      - type
      - details
      properties:
        type:
          description: type of insureds
          type: string
          example: USER
          enum:
          - USER
          - TRAVEL
          - EXPERIENCE
          - HOSPITALITY
          - LOAN
          - USER_LENDER
          - USER_BORROWER
          - GADGET
          - SHIPPING
          - PACKAGE
          - GOODS
          - VEHICLE
          - AGENT
        details:
          description: detail information of insureds
          type: object
          anyOf:
          - $ref: '#/components/schemas/InsuredTravel'
          - $ref: '#/components/schemas/InsuredUser'
          - $ref: '#/components/schemas/InsuredLoan'
          - $ref: '#/components/schemas/InsuredGadget'
          - $ref: '#/components/schemas/InsuredMotor'
          - $ref: '#/components/schemas/InsuredShipping'
          - $ref: '#/components/schemas/InsuredPackage'
          - $ref: '#/components/schemas/InsuredVehicle'
          - $ref: '#/components/schemas/InsuredGoods'
          - $ref: '#/components/schemas/InsuredAgent'
        documents:
          description: insured's supporting documents
          type: array
          items:
            $ref: '#/components/schemas/Document'
    200status:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: success get claim
        code:
          type: number
          example: 200
        data:
          type: object
          properties:
            policy_number:
              type: string
              example: 1234
            claims:
              type: array
              items:
                type: object
                properties:
                  number:
                    type: string
                    example: C-20240718-TFLIGHTPARTNER001-CXVAC2
                  status:
                    type: string
                    example: INSURANCE_CLAIM_APPROVE
                    oneOf:
                    - title: CLAIM_INITIATE
                      description: When the claimer successfully submitted a claim
                    - title: QOALA_CLAIM_APPROVE
                      description: Qoala approved the claim
                    - title: QOALA_CLAIM_REJECT
                      description: Qoala rejected the claim
                    - title: INSURANCE_CLAIM_APPROVE
                      description: Insurer approved the claim
                    - title: INSURANCE_CLAIM_REJECT
                      description: Insurer rejected the claim
                    - title: INSURANCE_CLAIM_PAID
                      description: Claim already paid by insurer
                  created_at:
                    type: string
                    example: '2023-10-11 20:00:00'
                    format: date-time
                  benefit_code:
                    type: string
                    example: BENEFIT_CODE
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  examples:
    createClaimTravelProduct:
      value:
        currency_code: IDR
        country_code: ID
        user_channel: PARTNERSHIP
        partner_code: ABC
        partner_claim_id: C12345
        policy_number: F-CRDT-PARTNER-001-20230802-OM94T
        total_amount: 100000
        product:
          category: TRAVEL
          code: PA-123
          benefit_code: BENEFIT_CODE
        claimant_data:
          full_name: string
          phone_number: '+6281234567890'
        form_data:
        - name: Alamat
          value: '85778'
        covered_data:
        - type: USER
          details:
            identity_type: KTP
            identity_number: '1234567890000000'
            full_name: Test
            email: jane.doe@qoala.id
            phone_number: '+6281234567890'
            birth_date: '1990-01-01'
            gender: MALE
            address: Jl. Sudirman No. 10, Kelurahan Menteng, Kecamatan Menteng, Kota Jakarta Pusat, DKI
              Jakarta 10310
            occupation: Software Engineer
            additional_info:
              passenger_type: ADULT
    createClaimPartnerResponse200:
      value:
        status: success
        message: Claim Service success
        code: 200
        data:
          number: C-20240718-TFLIGHTPARTNER001-CXVAC2
          policy_number: T-FLIGHT-PARTNER-001-20230824-OM94T
          last_status: CLAIM_INITIATE
          created_at: '2024-07-18T10:30:00Z'
    createClaimPartnerResponse500:
      value:
        code: 500
        error_code: CLAIM-ERR-001
        message: internal server error
        status: failed
    createClaimCreditInsuranceWithReinstatement:
      value:
        user_channel: PARTNERSHIP
        policy_number: T-FLIGHT-PARTNER-001-20230824-OM94T
        partner_code: PARTNER_CODE
        currency_code: IDR
        total_amount: 200000
        country_code: ID
        product:
          category: FINANCE
          code: F-CRDT-PARTNER-001
          benefit_code: BENEFIT_CODE
        claim_additional_info:
          loan_id: LOAN_ID
          borrower_name: BORROWERNAME
          beneficiary_name: BENEFICIARY_NAME
          last_payment_date: '2023-05-14T00:00:00.000Z'
          last_collection_date: '2023-05-14T00:00:00.000Z'
          outstanding_amount: 200000
